FROM ubuntu:20.04

MAINTAINER Seongjin Mun <sjin217@gmail.com>

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get -y dist-upgrade

RUN DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends apt-utils

RUN apt-get -y install software-properties-common git iproute2 redis-server apache2 vim
RUN apt-get -y install libapache2-mod-php php-redis php7.4-cli php7.4-bcmath php7.4-bz2 php7.4-common php7.4-curl php7.4-dba php7.4-gd php7.4-json php7.4-mbstring php7.4-opcache php7.4-readline php7.4-soap php7.4-xml php7.4-xmlrpc php7.4-zip php7.4-ctype php7.4-pdo php7.4-redis php7.4-mysql php7.4-imagick php7.4-intl

RUN sed -i 's/upload_max_filesize = 2M/upload_max_filesize = 100M/' /etc/php/7.4/apache2/php.ini
RUN sed -i 's/post_max_size = 8M/post_max_size = 100M/' /etc/php/7.4/apache2/php.ini

ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN wget http://caos.kldp.net/frs/download.php/4855/mod_url-apache2-1.15.tar.bz2
RUN bunzip2 mod_url-apache2-1.15.tar.bz2
RUN tar xvf mod_url-apache2-1.15.tar -C ./

RUN apxs -i -c mod_url.c

COPY ./url.conf /etc/apache2/mods-enabled/url.conf
COPY ./url.load /etc/apache2/mods-enabled/url.load

COPY ./000-default.conf /etc/apache2/sites-available/
COPY ./ /var/www/html/

RUN a2enmod rewrite

EXPOSE 80

CMD ["apachectl", "-D", "FOREGROUND"]f